spring:
  application:
    name: user_centers
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_centers
    username: root
    password: 123456
server:
  port: 8080